/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*- */
/* cm-enums.h
 *
 * Copyright 2022 Purism SPC
 *
 * Author(s):
 *   Mohammed Sadiq <sadiq@sadiqpk.org>
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

#pragma once


/**
 * CmError:
 *
 * The Error returned by the Matrix Server
 * See https://matrix.org/docs/spec/client_server/r0.6.1#api-standards
 * for details.
 */
typedef enum {
  M_FORBIDDEN = 1,
  M_UNKNOWN_TOKEN,
  M_MISSING_TOKEN,
  M_BAD_JSON,
  M_NOT_JSON,
  M_NOT_FOUND,
  M_LIMIT_EXCEEDED,
  M_UNKNOWN,
  M_UNRECOGNIZED,
  M_UNAUTHORIZED,
  M_USER_DEACTIVATED,
  M_USER_IN_USE,
  M_INVALID_USERNAME,
  M_ROOM_IN_USE,
  M_INVALID_ROOM_STATE,
  M_THREEPID_IN_USE,
  M_THREEPID_NOT_FOUND,
  M_THREEPID_AUTH_FAILED,
  M_THREEPID_DENIED,
  M_SERVER_NOT_TRUSTED,
  M_UNSUPPORTED_ROOM_VERSION,
  M_INCOMPATIBLE_ROOM_VERSION,
  M_BAD_STATE,
  M_GUEST_ACCESS_FORBIDDEN,
  M_CAPTCHA_NEEDED,
  M_CAPTCHA_INVALID,
  M_MISSING_PARAM,
  M_INVALID_PARAM,
  M_TOO_LARGE,
  M_EXCLUSIVE,
  M_RESOURCE_LIMIT_EXCEEDED,
  M_CANNOT_LEAVE_SERVER_NOTICE_ROOM,

  /* Local errors */
  M_BAD_PASSWORD,
  M_NO_HOME_SERVER,
  M_BAD_HOME_SERVER,
} CmError;


typedef enum {
  CM_ROOM_UNKNOWN,
  CM_ROOM_JOINED,
  CM_ROOM_LEFT,
  CM_ROOM_INVITED
} CmRoomType;

typedef enum {
  CM_STATUS_UNKNOWN,
  CM_STATUS_JOIN,
  CM_STATUS_LEAVE,
  CM_STATUS_INVITE,
  CM_STATUS_BAN,
  CM_STATUS_KNOCK
} CmStatus;

typedef enum {
  CM_CONTENT_TYPE_UNKNOWN,
  CM_CONTENT_TYPE_TEXT,
  CM_CONTENT_TYPE_EMOTE,
  CM_CONTENT_TYPE_NOTICE,
  CM_CONTENT_TYPE_IMAGE,
  CM_CONTENT_TYPE_FILE,
  CM_CONTENT_TYPE_AUDIO,
  CM_CONTENT_TYPE_LOCATION,
  CM_CONTENT_TYPE_VIDEO
} CmContentType;

/*
 * The order of the enum items SHOULD NEVER
 * be changed as they are used in database.
 * New items should be appended to the end.
 */
typedef enum {
  CM_M_UNKNOWN,
  CM_M_CALL_ANSWER,
  CM_M_CALL_ASSERTED_IDENTITY,
  CM_M_CALL_ASSERTED_IDENTITY_PREFIX,
  CM_M_CALL_CANDIDATES,
  CM_M_CALL_HANGUP,
  CM_M_CALL_INVITE,
  CM_M_CALL_NEGOTIATE,
  CM_M_CALL_REJECT,
  CM_M_CALL_REPLACES,
  CM_M_CALL_SELECT_ANSWER,
  CM_M_DIRECT,
  CM_M_DUMMY,
  CM_M_FORWARDED_ROOM_KEY,
  CM_M_FULLY_READ,
  CM_M_IGNORED_USER_LIST,
  CM_M_KEY_VERIFICATION_ACCEPT,
  CM_M_KEY_VERIFICATION_CANCEL,
  CM_M_KEY_VERIFICATION_DONE,
  CM_M_KEY_VERIFICATION_KEY,
  CM_M_KEY_VERIFICATION_MAC,
  CM_M_KEY_VERIFICATION_READY,
  CM_M_KEY_VERIFICATION_REQUEST,
  CM_M_KEY_VERIFICATION_START,
  CM_M_PRESENCE,
  CM_M_PUSH_RULES,
  CM_M_REACTION,
  CM_M_RECEIPT,
  CM_M_ROOM_ALIASES,
  CM_M_ROOM_AVATAR,
  CM_M_ROOM_CANONICAL_ALIAS,
  CM_M_ROOM_CREATE,
  CM_M_ROOM_ENCRYPTED,
  CM_M_ROOM_ENCRYPTION,
  CM_M_ROOM_GUEST_ACCESS,
  CM_M_ROOM_HISTORY_VISIBILITY,
  CM_M_ROOM_JOIN_RULES,
  CM_M_ROOM_KEY,
  CM_M_ROOM_KEY_REQUEST,
  CM_M_ROOM_MEMBER,
  CM_M_ROOM_MESSAGE,
  CM_M_ROOM_MESSAGE_FEEDBACK,
  CM_M_ROOM_NAME,
  CM_M_ROOM_PINNED_EVENTS,
  CM_M_ROOM_PLUMBING,
  CM_M_ROOM_POWER_LEVELS,
  CM_M_ROOM_REDACTION,
  CM_M_ROOM_RELATED_GROUPS,
  CM_M_ROOM_SERVER_ACL,
  CM_M_ROOM_THIRD_PARTY_INVITE,
  CM_M_ROOM_TOMBSTONE,
  CM_M_ROOM_TOPIC,
  CM_M_SECRET_REQUEST,
  CM_M_SECRET_SEND,
  CM_M_SECRET_STORAGE_DEFAULT_KEY,
  CM_M_SPACE_CHILD,
  CM_M_SPACE_PARENT,
  CM_M_STICKER,
  CM_M_TAG,
  CM_M_TYPING,

  /* Custom */
  CM_M_USER_STATUS = 256,
  CM_M_ROOM_INVITE,
  CM_M_ROOM_BAN,
  CM_M_ROOM_KICK,
} CmEventType;

typedef enum
{
  CM_EVENT_STATE_UNKNOWN,
  CM_EVENT_STATE_DRAFT,
  CM_EVENT_STATE_RECEIVED,
  /* When saving to db consider this as failed until sent? */
  CM_EVENT_STATE_SENDING,
  CM_EVENT_STATE_SENT,
  CM_EVENT_STATE_SENDING_FAILED,
} CmEventState;
